### ISSUE TITLE
question about  Global Protein Sequence Descriptors

### ISSUE THREAD

**Issue by flystar233** [tlawrence3/amPEPpy#1]
hi，Lawrence.
I am very interested in your research. But I don’t know much about Global Protein Sequence Descriptors.
I have read your python code, the score function part defines some characteristics of amino acids（hydrophobicity，polarity...)
Could you tell me its source？
Thanks.

`'hydrophobicity': {1: ['R', 'K', 'E', 'D', 'Q', 'N'], 2: ['G', 'A', 'S', 'T', 'P', 'H', 'Y'], 3: ['C', 'L', 'V', 'I', 'M', 'F', 'W']},
   'normalized.van.der.waals': {1: ['G', 'A', 'S', 'T', 'P', 'D', 'C'], 2: ['N', 'V', 'E', 'Q', 'I', 'L'], 3: ['M', 'H', 'K', 'F', 'R', 'Y', 'W']},
           'polarity': {1: ['L', 'I', 'F', 'W', 'C', 'M', 'V', 'Y'], 2: ['P', 'A', 'T', 'G', 'S'], 3: ['H', 'Q', 'R', 'K', 'N', 'E', 'D']},
           'polarizability': {1: ['G', 'A', 'S', 'D', 'T'], 2: ['C', 'P', 'N', 'V', 'E', 'Q', 'I', 'L'], 3: ['K', 'M', 'H', 'F', 'R', 'Y', 'W']},
           'charge': {1: ['K', 'R'], 2: ['A', 'N', 'C', 'Q', 'G', 'H', 'I', 'L', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'], 3: ['D', 'E']},
           'secondary': {1: ['E', 'A', 'L', 'M', 'Q', 'K', 'R', 'H'], 2: ['V', 'I', 'Y', 'C', 'W', 'F', 'T'], 3: ['G', 'N', 'P', 'S', 'D']},
           'solvent': {1: ['A', 'L', 'F', 'C', 'G', 'I', 'V', 'W'], 2: ['R', 'K', 'Q', 'E', 'N', 'D'], 3: ['M', 'S', 'P', 'T', 'H', 'Y']}`

**Comment by flystar233** [comment]
Done.

**Comment by tlawrence3** [comment]
Not sure if you are still looking for information on this @flystar233. The documentation for this R package ([https://cran.r-project.org/web/packages/protr/vignettes/protr.html](https://cran.r-project.org/web/packages/protr/vignettes/protr.html)) has a tutorial for how to calculate the CTD Global Protein Sequence Descriptors. These descriptors were originally described in this paper ([https://www.pnas.org/content/92/19/8700](https://www.pnas.org/content/92/19/8700)). Thanks for your interest!

**Comment by flystar233** [comment]
Thank you for providing such a detailed source of information.
By the way, 
The code `classify_df.to_csv('feature.txt',sep='\t',index_label="seq_name")` can be added after line 135.
