### ISSUE TITLE
ValueError: Number of features of the model must match the input.

### ISSUE THREAD

**Issue by cmerenstein** [tlawrence3/amPEPpy#2]
Hello,

I've been using amPEPpy for a little while now and it generally works well, but while trying to classify a group of sequences I got the following error:

ValueError: Number of features of the model must match the input. Model n_features is 105 and input n_features is 210

I have 2 fasta files - on one file amPEPpy works fine, on the other it gives me this error. I can't spot any differences between my 2 fasta files, but is there something I can do to narrow down what is causing this and what the difference might be?

Thanks for the help!

**Comment by tlawrence3** [comment]
Hi @cmerenstein,

Thanks for using amPEPpy and for reaching out with this error. To help figure out what is going on could you provide the command you are using that works and the command that doesn't work. Are you using the pre-trained model that we provided in the GitHub repo or did you train your own? Are you attempting to exclude features from training and prediction?

**Comment by cmerenstein** [comment]
The command is the same for both the working and not working version, what changes is either the peptides being tested, or the model being used.

The command is just:
ampep predict -m $model -i $fasta-o $AMP_output --seed 19002

For my first fasta file, all of my retrained models work. For the second fasta file, only the model trained on the training data from GitHub work.

Both files only include standard amino acids, peptides between 5 and 50 aa long.

**Comment by tlawrence3** [comment]
When you retrained your models did you exclude any features? If not, would it be possible for you to send the fasta files you used to train the model, the command used to train the model, and the second fasta file containing the sequences you attempted to classify to tlawrence3@ucmerced.edu?

**Comment by cmerenstein** [comment]
I figured it out!

Turns out two sequences in my fasta file had the same sequence ID. I guess the features of these were then being combined, giving the error of 210 features instead of 105.

**Comment by tlawrence3** [comment]
Perfect! In the next version we will add code to check for this.
